---
title: "pegas::amova"
author: "Brian J. Knaus"
date: "July 18, 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## pegas::amova


```{r}
#pegas::amova

foo <- function(x, index) unlist(lapply(split(x, index), sum))

# Get the sum of squared deviations
getSSD <- function(y, gr) {
  
  nsamp <- nrow(gr)
  Nlv <- ncol(gr)
  N <- lapply(gr, tabulate)
  
  SSD <- numeric(Nlv + 2)
  SSD[Nlv + 2] <- sum(y/(2 * nsamp))
  
  for (i in 1:Nlv) {
    p <- gr[, i]
    SSD[i + 1] <- sum(  (y/(2 * N[[i]])[p] )[outer(p, p, "==")] )
  }
  
  if (Nlv > 1){
    for (i in 2:Nlv){
      SSD[i] <- SSD[i] - SSD[i + 1]
    }
  }
  
  SSD[1] <- SSD[Nlv + 2] - sum(SSD[-(Nlv + 2)])
  return(SSD)
}


getDF <- function(gr) {
  nsamp <- nrow(gr)
  Nlv <- ncol(gr)
  N <- lapply(gr, tabulate)
  
  dfreedom <- numeric(Nlv + 2)
  dfreedom[1:Nlv] <- unlist(lapply(N, length))
  dfreedom[Nlv + 1] <- nsamp
  
  for (i in (Nlv + 1):2){
    dfreedom[i] <- dfreedom[i] - dfreedom[i - 1]
  }
  
  dfreedom[1] <- dfreedom[1] - 1
  dfreedom[Nlv + 2] <- nsamp - 1
  return( dfreedom )
}

getNcoefficient <- function(gr) {
  N <- lapply(gr, tabulate)
  nsamp <- nrow(gr)
  Nlv <- ncol(gr)
      
  Nig <- N[[Nlv]]
  Nig2 <- Nig^2
  npop <- length(Nig)
  
  if (Nlv == 1){
    ncoef <- (nsamp - sum(Nig2)/nsamp)/(npop - 1)
  } else {
    if (Nlv == 2) {
      ncoef <- numeric(3)
      G <- nlevels(gr[, 1])
      g <- gr[, 1][match(1:npop, as.integer(gr[, 2]))]
      npopBYgr <- tabulate(g)
      A <- sum(foo(Nig2, g)/foo(Nig, g))
      ncoef[1] <- (nsamp - A)/sum(npopBYgr - 1)
      ncoef[2] <- (A - sum(Nig2)/nsamp)/(G - 1)
      ncoef[3] <- (nsamp - sum(foo(Nig, g)^2/nsamp))/(G - 1)
    } else {
      ncoef <- numeric(Nlv + 1)
      ncoef[Nlv] <- (nsamp - sum(Nig2)/nsamp)/(npop - 1)
      ncoef[Nlv + 1] <- 1
      
      for (i in 1:(Nlv - 1)) {
        group <- gr[, i]
        g <- group[match(1:npop, as.integer(gr[, i + 1]))]
        A <- sum(foo(Nig, g)^2)/sum(foo(Nig, g))
        ncoef[i] <- (nsamp - A)/(nlevels(group) - 1)
      }
    }
  }
  
  names(ncoef) <- letters[1:length(ncoef)]
  return(ncoef)
}


getVarComp <- function(gr, MSD) {
 
  nsamp <- nrow(gr)
  ncoef <- getNcoefficient(gr)
  N <- lapply(gr, tabulate)
  Nlv <- ncol(gr)
  
  if (Nlv == 1){
    sigma2 <- c((MSD[1] - MSD[2])/ncoef, MSD[2])
  } else {
    sigma2 <- numeric(Nlv + 1)
    if (Nlv == 2) {
      sigma2[3] <- MSD[3]
      sigma2[2] <- (MSD[2] - sigma2[3])/ncoef[1]
      sigma2[1] <- (MSD[1] - MSD[3] - ncoef[2] * sigma2[2])/ncoef[3]
    } else {
      sigma2[Nlv + 1] <- MSD[Nlv + 1]
      for (i in Nlv:1) {
        sel <- i:(Nlv + 1)
        sigma2[i] <- (MSD[i] - sum(ncoef[sel] * sigma2[sel]))/ncoef[i]
      }
    }
  }
  
  names(sigma2) <- c(names(gr), "Error")
  return( sigma2 )
}

    
permutation_test <- function(nperm, sigma2, y, gr){
  
  nsamp <- nrow(gr)
  # Number of levels
  Nlv <- length(gr)
  N <- lapply(gr, tabulate)
  dfreedom <- getDF(gr)

        rSigma2 <- matrix(0, nperm, length(sigma2))
        j <- if (Nlv == 1) 
            1:2
        else Nlv + 1
        for (i in 1:nperm) {
            rY <- perm.rowscols(y, nsamp)
            rSSD <- getSSD(rY, gr)
            rSigma2[i, j] <- getVarComp(gr, rSSD/dfreedom)[j]
        }
        if (Nlv > 1) {
            j <- Nlv
            L <- lapply(levels(gr[, j - 1]), function(x) which(gr[, 
                j - 1] == x))
            for (i in 1:nperm) {
                rind <- unlist(lapply(L, sample))
                rY <- y[rind, rind]
                rSSD <- getSSD(rY, gr)
                rSigma2[i, j] <- getVarComp(gr, rSSD/dfreedom)[j]
            }
            if (Nlv > 2) {
                for (j in (Nlv - 1):2) {
                  above <- gr[, j - 1]
                  L <- lapply(levels(above), function(x) which(above == 
                    x))
                  for (i in 1:nperm) {
                    rind <- integer(0)
                    for (k in L) rind <- c(rind, sample(k))
                    rind <- unlist(lapply(L, sample))
                    rY <- y[rind, rind]
                    rGR <- gr[rind, ]
                    rN <- lapply(rGR, tabulate)
                    rSSD <- getSSD(rY, rGR)
                    rDF <- getDF(rGR)
                    rNcoef <- getNcoefficient(rGR)
                    rSigma2[i, j] <- getVarComp(gr, rSSD/rDF)[j]
                  }
                }
            }
            N2 <- N[[2]]
            Higr <- gr[, 1][cumsum(N2)]
            rGR <- gr
            for (i in 1:nperm) {
                rGR[, 1] <- unlist(mapply(rep, sample(Higr), 
                  each = N2, SIMPLIFY = FALSE))
                rN <- lapply(rGR, tabulate)
                rSSD <- getSSD(rY, rGR)
                rDF <- getDF(rGR)
                rNcoef <- getNcoefficient(rGR)
                rSigma2[i, 1] <- getVarComp(gr, rSSD/rDF)[1]
            }
        }
        P <- numeric(Nlv + 1)
        for (j in 1:(Nlv + 1)) P[j] <- sum(rSigma2[, j] >= sigma2[j])/(nperm + 
            1)
        P[Nlv + 1] <- NA
#        res$varcomp <- data.frame(sigma2 = res$varcomp, P.value = P)
#        return( data.frame(sigma2 = res$varcomp, P.value = P) )
        return( P )
}
```



```{r}
repAmova <- function (formula, data = NULL, nperm = 10, is.squared = FALSE) 
{

    # Set environment
    data.env <- if (is.null(data)){
      environment(formula)
    } else {
      as.environment(data)
    }
    
    # The left hand side is a distance matrix
    # Manage left hand side
    y.nms <- as.character(as.expression(formula[[2]]))
    # load lhs into y
    y <- get(y.nms, envir = environment(formula))
    # Sanitize lhs dist/matrix
    if (any(is.na(y))) 
        warning("at least one missing value in the distance object.")
    if (!is.squared) 
        y <- y^2
    if (class(y) == "dist") 
        y <- as.matrix(y)
    if (!is.matrix(y)) 
        stop("the lhs of the formula must be either a matrix or an object of class 'dist'.")
    
    # Manage right hand side
    rhs <- formula[[3]]
    gr.nms <- as.character(as.expression(rhs))
    if (length(rhs) > 1) 
        gr.nms <- unlist(strsplit(gr.nms, "/"))
    # Test that rhs are factors
    if (any(sapply(gr.nms, function(x) !is.factor(get(x, envir = data.env))))) 
        warning("elements in the rhs of the formula are not all factors")
    # Load rhs data in gr
    gr <- as.data.frame(sapply(gr.nms, get, envir = data.env))

    nsamp <- nrow(gr)
    Nlv <- ncol(gr)
#    nsamp <- dim(y)[1]
    # Number of levels
#    Nlv <- length(gr)

    # AMOVA
    N <- lapply(gr, tabulate)
    SSD <- getSSD(y, gr)
    dfreedom <- getDF(gr)
    MSD <- SSD/dfreedom
    ncoef <- getNcoefficient(gr)
    sigma2 <- getVarComp(gr, MSD)
    
    # Assemble return
    res <- list(tab = data.frame(SSD = SSD, MSD = MSD, df = dfreedom, 
        row.names = c(names(gr), "Error", "Total")), varcoef = ncoef, 
        varcomp = sigma2, call = match.call())
    class(res) <- "amova2"
    
    # Permutation test
    if (nperm) {
      P.value <- permutation_test(nperm, sigma2, y, gr)
      res$varcomp <- data.frame(sigma2 = res$varcomp, P.value = P.value)
    }
    
    res
}
```



```{r}
print.amova2 <- function(x, ...)
{
    cat("\n\tBJK Analysis of Molecular Variance\n\nCall: ")
    print(x$call)
    cat("\n")
    print(x$tab)
    cat("\nVariance components:\n")
    if (is.data.frame(x$varcomp)) {
        x$varcomp["Error", "P.value"] <- NA
        printCoefmat(x$varcomp, na.print = "")
    } else print(x$varcomp)
    cat("\nVariance coefficients:\n")
    print(x$varcoef)
    cat("\n")
}
```



```{r}
### All examples below have 'nperm = 100' for faster execution times.
### The default 'nperm = 1000' is recommended.
require(ape)
data(woodmouse)
d <- dist.dna(woodmouse)
g <- factor(c(rep("A", 7), rep("B", 8)))
p <- factor(c(rep(1, 3), rep(2, 4), rep(3, 4), rep(4, 4)))
#amova(d ~ g/p, nperm = 100) # 2 levels
#amova(d ~ p, nperm = 100) # 1 level
#amova(d ~ g, nperm = 100)

#debug(repAmova)
#undebug(permutation_test)

repAmova(d ~ g/p, nperm = 00) # 2 levels
repAmova(d ~ p, nperm = 100) # 1 level
repAmova(d ~ g, nperm = 100)


```



